image_dir: ""     # Path to directory holding images
mask_dir: ""                         # path to the directory of masked cell images. ***It is assumed there is a one-to-one correspondence between data and masks!!!***
image_type: ""                    # Image filetype (nd2 or tiff/tif)
spot_out: ""                  # output directory for spots

channels:                            # channels included in images (in order, 0th, 1st, 2nd, etc)
 - ""
spot_channel: ""                 # name of channel to call spots on (i.e. "Cy3")
stack: true                          # true if the image is a stack (Z stack), false otherwise 
piscis_thresh: 1                     # piscis spot calling threshold - make only small changes to this value [0..1]
piscis_scale: 1                      # piscis scale param
piscis_min_distance: 1               # piscis minimum distance param
expand_mask: 0                     # pixel amount to expand all masks by

custom_model: true
model_dir: ""
model: "l"                    #  name of the piscis model to use for spot calling

plot_max: true                       # plot all dots on each z stack independently
plot_z: true                         # plot all dots on their respective z levels        
plot_out_dir: "./plots"                    # output directory for plots

